# This is a basic workflow to help you get started with Actions

name: code-sync

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  sync:
    runs-on: ubuntu-latest
    env:
     repo-source: ${{secrets.REPO_SOURCE}}
    steps:
        - uses: actions/checkout@v2
        - name: Run a command remotely
          uses: docker://evaneos/ssh-action:0.1.0
          with:
           hosts: ${{ secrets.SSH_HOST }}
           user: ${{ secrets.SSH_USER }}
           password: ${{ secrets.SSH_PASSWORD }}
           commands: |
             sudo cd  ${{secrets.REPO_SOURCE}}
             sudo git pull
             sudo chmod +x script.sh
             sudo ./script.sh


